import type { Address, Category, Medicine, Profile } from '@elhazem/shared'

// بيانات وهمية للوضع التجريبي (بدون مشروع Supabase) — نفس بيانات supabase/migrations/0005_seed.sql
// تقريبًا، عشان اللي بيجرب الموقع يشوف شكله الحقيقي بأدوية وأقسام حقيقية.

export const demoCategories: Category[] = [
  { id: 'cat-pain', nameAr: 'مسكنات وخافضات حرارة', slug: 'pain-relief', sortOrder: 1 },
  { id: 'cat-vitamins', nameAr: 'فيتامينات ومكملات', slug: 'vitamins', sortOrder: 2 },
  { id: 'cat-cold', nameAr: 'أدوية البرد والانفلونزا', slug: 'cold-flu', sortOrder: 3 },
  { id: 'cat-skin', nameAr: 'العناية بالبشرة', slug: 'skincare', sortOrder: 4 },
  { id: 'cat-chronic', nameAr: 'أدوية مزمنة', slug: 'chronic', sortOrder: 5 },
]

const now = new Date().toISOString()

export const demoMedicines: Medicine[] = [
  {
    id: 'med-panadol',
    nameAr: 'بانادول اكسترا',
    nameEn: 'Panadol Extra',
    descriptionAr: 'مسكن وخافض حرارة، ٢٤ قرص — مناسب لآلام الصداع والحمى الخفيفة.',
    categoryId: 'cat-pain',
    sku: 'MED-001',
    manufacturer: 'GSK',
    price: 25,
    stockQuantity: 200,
    requiresPrescription: false,
    imageUrl: null,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'med-feroglobin',
    nameAr: 'فيروجلوبين كبسول',
    nameEn: 'Feroglobin',
    descriptionAr: 'مكمل حديد وفيتامينات، ٣٠ كبسولة — لدعم مستوى الحديد الطبيعي بالجسم.',
    categoryId: 'cat-vitamins',
    sku: 'MED-002',
    manufacturer: 'Vitabiotics',
    price: 180,
    stockQuantity: 80,
    requiresPrescription: false,
    imageUrl: null,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'med-congestal',
    nameAr: 'كونجستال',
    nameEn: 'Congestal',
    descriptionAr: 'أقراص لأعراض البرد والانفلونزا، ٢٠ قرص.',
    categoryId: 'cat-cold',
    sku: 'MED-003',
    manufacturer: 'Sigma',
    price: 30,
    stockQuantity: 150,
    requiresPrescription: false,
    imageUrl: null,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'med-augmentin',
    nameAr: 'أوجمنتين ١ جم',
    nameEn: 'Augmentin 1g',
    descriptionAr: 'مضاد حيوي، ١٤ قرص — يستلزم روشتة طبية.',
    categoryId: 'cat-chronic',
    sku: 'MED-004',
    manufacturer: 'GSK',
    price: 95,
    stockQuantity: 60,
    requiresPrescription: true,
    imageUrl: null,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'med-cetaphil',
    nameAr: 'سيتافيل مويستشرايزر',
    nameEn: 'Cetaphil Moisturizer',
    descriptionAr: 'كريم ترطيب للبشرة الحساسة، ٢٥٠ مل.',
    categoryId: 'cat-skin',
    sku: 'MED-005',
    manufacturer: 'Galderma',
    price: 350,
    stockQuantity: 40,
    requiresPrescription: false,
    imageUrl: null,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'med-vitaminc',
    nameAr: 'فيتامين سي فوار',
    nameEn: 'Vitamin C Effervescent',
    descriptionAr: 'أقراص فوارة لدعم المناعة، ٢٠ قرص.',
    categoryId: 'cat-vitamins',
    sku: 'MED-006',
    manufacturer: 'Bayer',
    price: 45,
    stockQuantity: 120,
    requiresPrescription: false,
    imageUrl: null,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
]

export const demoProfile: Profile = {
  id: 'demo-customer',
  fullName: 'عميل تجريبي',
  phone: '01000000000',
  role: 'customer',
  expoPushToken: null,
  createdAt: now,
}

export const demoAddress: Address = {
  id: 'demo-address',
  customerId: 'demo-customer',
  label: 'المنزل',
  governorate: 'القاهرة',
  city: 'مدينة نصر',
  street: 'شارع مصطفى النحاس',
  building: '12',
  floor: '3',
  apartment: '7',
  landmark: 'بجوار سيتي ستارز',
  lat: 30.0731,
  lng: 31.3467,
  isDefault: true,
  createdAt: now,
}
